### PR TITLE
Update simulation page

### PR DESCRIPTION
**Pull request by Ven0mX**

### CODE REVIEW

**Comment by ccedric** [comment]
I think you did a mistake, you deleted a screenshot showing gatling-enterprise, and added a screenshot showing gatling-frontline

**Comment by Ven0mX** [comment]
> I think you did a mistake, you deleted a screenshot showing gatling-enterprise, and added a screenshot showing gatling-frontline

yes I've  just corrected it.

**Comment by ccedric** [comment]
I don't see the point of this pr, you seem to have already updated this part, and the two screenshots are identical.

**Review by Isammoc — APPROVED** [review]

**Comment by Isammoc** [comment]
> I don't see the point of this pr, you seem to have already updated this part, and the two screenshots are identical.

@ccedric The purpose is to remove his extension icon in the text inputs.
(easier to spot with swipe or onion skin diff)

**Review by ccedric — APPROVED** [review]

**Pull request merged**
