### PR TITLE
chore: Update documentation for private locations, closes CLOUD-2347

### PR DESCRIPTION
**Pull request by ccedric**
Modifications:
- Updated simulations page
- Added private locations page
- enable the use of include-code

todo:
- network diagram
- detailed description on how to install on Fargate and ec2
- document which url should be white-listed (or do we only tell them about the domain?)
- update simulation location config when new version drop

### CODE REVIEW

**Review by slandelle — CHANGES_REQUESTED** [review]
We should explain how to install the control plane once the customer has access to (DockerHub?):
* ECS + EC2
* ECS + Fargate + the sidecar that downloads from S3

**Comment by ccedric** [comment]
> We should explain how to install the control plane once the customer has access to (DockerHub?):
> 
> * ECS + EC2
> * ECS + Fargate + the sidecar that downloads from S3
> 
> Also, we must add a network connections diagram.

Indeed, this PR is still in WIP, I'll let people more advanced on AWS describe how to configure fargate / EC2

**Comment by tpetillot** [comment]
Alternative proposal: https://github.com/gatling/frontline-cloud-doc/pull/118

**Review by tpetillot — COMMENTED** [review]
Alternative proposal: https://github.com/gatling/frontline-cloud-doc/pull/118

**Pull request closed without merging**
